# Generated by Django 5.2.4 on 2025-07-22 05:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_auto_20250722_0807"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customer",
            name="store_custo_first_n_a7e990_idx",
        ),
        migrations.AlterModelTable(
            name="customer",
            table=None,
        ),
    ]
